# Python Data Science

# NumPy

In [1]:
import numpy as np

## Exercicio 1

Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.


In [ ]:
array = np.array(np.random.randint(10, 101, size=(50))) #variavel array contem o randint de 10 ate 100, com 50, unidimensional
print(array)
print(len(array)) #prova real para ver se tinha acertado
print(min(array)) #valor minimo atual
print(max(array)) #valor maximo


[ 90  29  25  41  22  86  70  66  76  17  46  11  35  42  54  98  10  60
  32  87  99  77  86  84  60  82  48  18  30  29  76  48  19  55  81  22
  12  94  11  17  56 100  21  83  98  82  74  86  38  93]
50
10
100


## Exercicio 2

Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha.


In [ ]:
array = np.array(np.random.randint(1, 17, size=(4, 4))) # mesma coisa do exe acima, mas com 1 até 16 random, matriz 4x4
print(f' Array: \n{array}\n') # ver o total
ultima_linha = array[-1, :] # '-1, :' pega a ultima linha, no pdf de exemplo tinhamos o de primeira linha: '[0, :]'
print(f'ultima linha: {ultima_linha}')

 Array: 
[[12 13 14 13]
 [ 2 12 13  4]
 [15 14 14  5]
 [ 2 11  7 11]]

ultima linha: [ 2 11  7 11]


## Exercicio 3

Crie um array de zeros com comprimento 15 e substitua os valores da 5a a 10a posicao por 1.


In [40]:
array = np.array(np.zeros(15)) #gera o array uni com 15 zeros
print(array)
array[4:10] = 1 #posicao de 5 ate 10 nao indice de 5 ate 10
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


## Exercicio 4

Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.


In [65]:
array = np.array(np.random.randint(0, 101, size=100)) #aleatorio, com 100 uni
print(array)
mediana = np.median(array) #calcula a mediana
print(mediana)
moda = np.bincount(array).argmax() #moda
print(moda)

[70 73 84  6 75 97 42 87 46 74 24 92 45 43 70 15 73 19 10 37 99  6 87 49
 71  8 34 99 20 43 97 29 58 66 69 74 36 49 42 19 38 49 29 20 40 24 39 80
 80 24  7 75 99 72 41 43 42 12 54 30 76 27 42 50 69 17 89 60 36 86 25 48
 38 61 72 69  2 65 61 64 49 95 27 58 66 63 30 96 82 71 43 51 57 15  5 63
 38 69 10 27]
49.0
42


## Exercicio 5

Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.


In [68]:
array = np.array(np.random.randint(1, 101, size=20)) # aleatorio entre 1 ate 100, com 20 uni
print(array)
for n in array: #listando cada indice
    if n % 3 == 0: #mod de 3, se for multiplo
        array[array == n] = -3 #substitui
print(array) 

[94 26  9 67 54 94 49 59  3 69 40 51 72 14 16 79 25 70 76 25]
[94 26 -3 67 -3 94 49 59 -3 -3 40 -3 -3 14 16 79 25 70 76 25]


## Exercicio 6

Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.


In [111]:
array = np.array(np.random.randint(0, 2, size=(5, 5))) #matriz 5x5 aleteatorio entre 0 e 1
print(array)
for col in range(array.shape[1]): #col ve o tamanho do array e circula ele
    soma = np.sum(array[:, col]) # ':' pega do indice 0 até 'col' que é o tamanho do array
    print(f'coluna {col}: {soma}')


[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 1 0 1]
 [0 0 0 0 0]
 [0 1 1 1 1]]
coluna 0: 1
coluna 1: 3
coluna 2: 3
coluna 3: 2
coluna 4: 3


## Exercicio 7

Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.


In [ ]:
array1 = np.array(np.random.randint(0, 10, size=(3))) #testei com 5, 2, e 3. 5 ficou dificil de entender 2 ficou muito binário, 3 ficou bom
array2 = np.array(np.random.randint(0, 10, size=(3)))
print(f'\n{array1}\n')
print(f'\n{array2}\n')

correlacao = np.corrcoef(array1, array2) #tinha usado antes a funcao correlate, porque n sabia o nome da certa
print(f'correlacao: \n{correlacao}\n') # correlacao muda quando gero os arrays, tenho indicativos de alta e baixa -1 ate 1

'''Legal observar que quando uma sobe a outra desce (correlacao)'''

#correlacao = np.correlate(array1, array2, mode='full')
#print(f'\ncorrelacao: {correlacao}\n')



[0 6 1]


[9 8 0]

correlacao: 
[[1.         0.26276513]
 [0.26276513 1.        ]]



## Exercicio 8

Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.


In [116]:
array = np.array(np.random.randint(1, 11, size=(3, 3)))
print(array)
for linha in range(0, 3):
    for coluna in range(0, 3):
        quadrado = array[linha][coluna] ** 2

print(quadrado)

[[10  1 10]
 [ 7  7  2]
 [ 3  2  8]]
64


## Exercicio 9

Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.


## Exercicio 10

Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.


## Exercicio 11

Gere um array de 100 numeros inteiros e encontre o valor que mais se repete no array.


## Exercicio 12

Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.


## Exercicio 13

Crie um array contendo os 10 primeiros numeros pares e calcule sua soma cumulativa.


## Exercicio 14

Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo comprimento e encontre a media das diferencas.


## Exercicio 15

Gere um array contendo 20 numeros e substitua todos os valores maiores que 50 por 50.


## Exercicio 16

Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.


## Exercicio 17

Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada valor por sua posicao na matriz.


## Exercicio 18

Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 5 por 0.


## Exercicio 19

Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o angulo entre eles (produto escalar normalizado).


## Exercicio 20

Crie uma matriz de numeros inteiros e encontre o valor minimo de cada linha.


# SciPy

## Exercicio 1

Calcule a integral da funcao f(x) = x^2 sin(x) no intervalo de 0 a pi.


## Exercicio 2

Resolva a equacao diferencial dy/dx = x - y, com y(0) = 1, no intervalo de 0 a 10.


## Exercicio 3

Encontre as raizes da funcao f(x) = x^4 - 3x^3 + 2 utilizando SciPy.


## Exercicio 4

Use a funcao de otimizacao de SciPy para maximizar f(x) = -x^2 + 4x + 1.


## Exercicio 5

Calcule a transformada de Fourier de um sinal composto de sin(2 pi t) e cos(4 pi t).


## Exercicio 6

Encontre a matriz inversa de uma matriz 5x5 de numeros aleatorios.


## Exercicio 7

Use a funcao de interpolacao cubica de SciPy para interpolar os dados (0, 0), (1, 2), (2, 3), (3, 5), (4, 4).


## Exercicio 8

Resolva o sistema de equacoes 3x + 2y = 5 e x + 4y = 6.


## Exercicio 9

Ajuste uma curva quadratica aos pontos (1, 2), (2, 4), (3, 5), (4, 7), (5, 8).


## Exercicio 10

Calcule a integral dupla da funcao f(x, y) = xy + x^2 no intervalo [0, 2] para x e [0, 1] para y.


## Exercicio 11

Encontre os autovalores e autovetores de uma matriz 4x4 de numeros inteiros aleatorios.


## Exercicio 12

Resolva a equacao e^x - x^2 = 0 para encontrar a raiz mais proxima de x = 1.


## Exercicio 13

Calcule o determinante de uma matriz 6x6 de numeros aleatorios entre -10 e 10.


## Exercicio 14

Utilize a funcao de otimizacao multivariada para minimizar f(x, y) = (x - 2)^2 + (y - 3)^2.


## Exercicio 15

Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.


## Exercicio 16

Resolva a equacao diferencial de segunda ordem d^2y/dx^2 + y = 0, com condicoes iniciais y(0) = 1 e y'(0) = 0.


## Exercicio 17

Encontre a raiz cubica de 27 utilizando SciPy.


## Exercicio 18

Interpole os valores de uma funcao f(x) = x^2 nos pontos [1, 2, 3, 4, 5] utilizando spline cubica.


## Exercicio 19

Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.


## Exercicio 20

Resolva um sistema de equacoes lineares com tres variaveis utilizando SciPy.


# Pandas

## Exercicio 1

Crie um DataFrame contendo as colunas Produto, Preco e Quantidade com 5 produtos.


## Exercicio 2

Leia um arquivo Excel chamado vendas.xlsx e exiba as 10 primeiras linhas.


## Exercicio 3

Filtre um DataFrame para exibir apenas os valores onde a coluna Preco e maior que 100.


## Exercicio 4

Adicione uma coluna chamada Desconto ao DataFrame com 10% de desconto para todos os produtos.


## Exercicio 5

Remova as linhas do DataFrame que contenham valores nulos.


## Exercicio 6

Ordene o DataFrame pela coluna Produto em ordem alfabetica.


## Exercicio 7

Crie uma nova coluna chamada Total que seja o produto entre as colunas Preco e Quantidade.


## Exercicio 8

Agrupe o DataFrame pela coluna Categoria e calcule o total de produtos por categoria.


## Exercicio 9

Exporte o DataFrame resultante para um arquivo CSV chamado resultados.csv.


## Exercicio 10

Leia um arquivo CSV, renomeie as colunas e exiba as 5 ultimas linhas do DataFrame.


## Exercicio 11

Preencha os valores nulos de uma coluna numerica com a mediana dessa coluna.


## Exercicio 12

Verifique quais colunas de um DataFrame contem valores duplicados.


## Exercicio 13

Crie uma tabela dinamica a partir do DataFrame, calculando a soma de Quantidade por Categoria.


## Exercicio 14

Mescle dois DataFrames baseados em uma coluna comum chamada ID utilizando um join.


## Exercicio 15

Crie um DataFrame com dados faltantes e use a interpolacao linear para preenche-los.


## Exercicio 16

Crie um grafico de barras a partir de um DataFrame usando a biblioteca Pandas.


## Exercicio 17

Adicione uma coluna ao DataFrame que calcule o imposto (5%) sobre o valor da coluna Total.


## Exercicio 18

Exiba apenas as linhas de um DataFrame onde o nome do produto comeca com a letra B.


## Exercicio 19

Crie um DataFrame a partir de um dicionario de listas e calcule a media de cada coluna numerica.


## Exercicio 20

Agrupe os dados por uma coluna categorica e calcule a mediana de uma coluna numerica.


# Matplotlib

## Exercicio 1

Crie um grafico de linha para a funcao y = x^3 no intervalo de x = -10 ate x = 10.


## Exercicio 2

Plote um grafico de dispersao para 100 pontos aleatorios com uma paleta de cores baseada nos valores de y.


## Exercicio 3

Gere um histograma para 500 numeros inteiros gerados aleatoriamente entre 0 e 100.


## Exercicio 4

Crie um grafico de barras para 5 categorias com valores diferentes, colorindo cada barra de uma cor diferente.


## Exercicio 5

Faca um grafico de pizza para representar as porcentagens de quatro setores de mercado com rotulos personalizados.


## Exercicio 6

Plote dois graficos de linha em subplots diferentes: y1 = e^x e y2 = log(x).


## Exercicio 7

Crie um grafico de dispersao com tamanho dos pontos variando de acordo com os valores de y.


## Exercicio 8

Plote um grafico de linha com intervalos de confianca (sombramento) para a funcao y = sin(x).


## Exercicio 9

Adicione titulo, rotulos e uma grade personalizada a um grafico de linha.


## Exercicio 10

Plote tres graficos de linha em um unico grafico, cada um com uma cor e estilo de linha diferentes.


## Exercicio 11

Crie um grafico de barras empilhadas para tres categorias com tres grupos de valores.


## Exercicio 12

Plote um grafico de linha com uma funcao quadratica e ajuste os limites do eixo para focar nos valores x = -5 a x = 5.


## Exercicio 13

Gere um grafico de dispersao 3D para 100 pontos aleatorios utilizando Matplotlib.


## Exercicio 14

Crie um grafico de barras horizontal para 4 categorias com valores gerados aleatoriamente.


## Exercicio 15

Plote a funcao y = 1/x com x variando de 1 a 100.


## Exercicio 16

Crie um grafico de linha com titulos para cada eixo e adicione um rotulo de texto no ponto x = 5.


## Exercicio 17

Plote um grafico de linha e salve-o como um arquivo PDF.


## Exercicio 18

Crie um grafico de barras com valores positivos e negativos e use diferentes cores para cada tipo de valor.


## Exercicio 19

Plote um grafico de linha com duas series e adicione uma legenda para diferencia-las.


## Exercicio 20

Adicione uma grade com espacamento personalizado a um grafico de linha para y = x^2.
