# Python Data Science

# NumPy

In [1]:
import numpy as np

## Exercicio 1

Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.


In [2]:
array = np.array(np.random.randint(10, 101, size=(50))) #variavel array contem o randint de 10 ate 100, com 50, unidimensional
print(array)
print(len(array)) #prova real para ver se tinha acertado
print(min(array)) #valor minimo atual
print(max(array)) #valor maximo


[ 29  84  92  98  84  63  12  75  97  55  55  42  15  41  60  33  51  25
  36  18  47  49  64  50  61  86  68 100  85  51  91  78  19  10  12  16
  19  11  33  81  35  84  48  94  82  51  90  61  44  52]
50
10
100


## Exercicio 2

Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha.


In [3]:
array = np.array(np.random.randint(1, 17, size=(4, 4))) # mesma coisa do exe acima, mas com 1 até 16 random, matriz 4x4
print(f' Array: \n{array}\n') # ver o total
ultima_linha = array[-1, :] # '-1, :' pega a ultima linha, no pdf de exemplo tinhamos o de primeira linha: '[0, :]'
print(f'ultima linha: {ultima_linha}')

 Array: 
[[ 1  8  4  8]
 [ 8 16  8 16]
 [16  7 15 16]
 [ 9 14  7  8]]

ultima linha: [ 9 14  7  8]


## Exercicio 3

Crie um array de zeros com comprimento 15 e substitua os valores da 5a a 10a posicao por 1.


In [4]:
array = np.array(np.zeros(15, dtype=int)) #gera o array uni com 15 zeros
print(array)
array[4:10] = 1 #posicao de 5 ate 10 nao indice de 5 ate 10
print(array)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]


## Exercicio 4

Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.


In [5]:
array = np.array(np.random.randint(0, 101, size=100)) #aleatorio, com 100 uni
print(array)
mediana = np.median(array) #calcula a mediana
print(mediana)
moda = np.bincount(array).argmax() #moda
print(moda)

[ 40  99  64  85   6  74  78  16  15  88  65  80  21  54  44  34  55  91
  99  51  97  50  17   1  54  88  96  10  97   3  10   6  61  34  80  19
  39  26  20  62  42  23  48  55  37  42  87  28  30  79  32  93  49 100
  15  15  84  62  36  24  61  14  94  40  25  69  13  98  67  62  35  87
  52  21  12  20  88  21  43  52   2   8  41  57  48  97  80  14  75   2
  14  48  40   1  72  58  46  31  65   8]
47.0
14


## Exercicio 5

Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.


In [6]:
array = np.array(np.random.randint(1, 101, size=20)) # aleatorio entre 1 ate 100, com 20 uni
print(array)
for n in array: #listando cada indice
    if n % 3 == 0: #mod de 3, se for multiplo
        array[array == n] = -3 #substitui
print(array) 

[17 27 19 23 84 47 50 66 59 31  6 45 51 76 85 60 15 52 90 79]
[17 -3 19 23 -3 47 50 -3 59 31 -3 -3 -3 76 85 -3 -3 52 -3 79]


## Exercicio 6

Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.


In [7]:
array = np.array(np.random.rand(5, 5)) #matriz 5x5 aleteatorio entre 0 e 1
print(array)
for col in range(array.shape[1]): #col ve o tamanho do array e circula ele
    soma = np.sum(array[:, col]) # ':' pega do indice 0 até 'col' que é o tamanho do array
    print(f'coluna {col}: {soma}')


[[0.62667331 0.93610363 0.64473502 0.52276138 0.35453432]
 [0.37086733 0.76517033 0.04789261 0.15743978 0.1393976 ]
 [0.04233448 0.01675759 0.36243152 0.89236849 0.55656931]
 [0.47676191 0.73503868 0.43387929 0.02258168 0.46311449]
 [0.96772006 0.24563343 0.47171861 0.94520252 0.80063289]]
coluna 0: 2.4843570926756353
coluna 1: 2.6987036549812764
coluna 2: 1.9606570453639778
coluna 3: 2.5403538561589305
coluna 4: 2.3142486136183567


## Exercicio 7

Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.


In [8]:
array1 = np.array(np.random.randint(0, 10, size=(3))) #testei com 5, 2, e 3. 5 ficou dificil de entender 2 ficou muito binário, 3 ficou bom
array2 = np.array(np.random.randint(0, 10, size=(3)))
print(f'\n{array1}\n')
print(f'\n{array2}\n')

correlacao = np.corrcoef(array1, array2) #tinha usado antes a funcao correlate, porque n sabia o nome da certa
print(f'correlacao: \n{correlacao}\n') # correlacao muda quando gero os arrays, tenho indicativos de alta e baixa -1 ate 1

'''Legal observar que quando uma sobe a outra desce (correlacao)'''

#correlacao = np.correlate(array1, array2, mode='full')
#print(f'\ncorrelacao: {correlacao}\n')



[6 4 3]


[6 5 3]

correlacao: 
[[1.         0.92857143]
 [0.92857143 1.        ]]



'Legal observar que quando uma sobe a outra desce (correlacao)'

## Exercicio 8

Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.


In [9]:
array = np.array(np.random.randint(1, 11, size=(3, 3)))
print(array)
for linha in range(0, 3):
    for coluna in range(0, 3):
        quadrado = array[linha][coluna] ** 2

#print(array**2)
print(quadrado)

[[ 2  7  5]
 [ 2  5  2]
 [10 10  2]]
4


## Exercicio 9

Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.


In [10]:
array = np.array(np.random.rand(10))
print(array)
max = np.max(array)

min = np.min(array)

print(f'\nMax: {max}\nMin: {min}\n')

lista = []

for n in array:

    normalize = (n - min) / (max - min)

    lista.append(normalize)

array_final = np.array(lista)
    

print(f'Array normalizado: {array_final}')

[0.82155288 0.96036217 0.39765412 0.53544069 0.90649993 0.00837397
 0.3876787  0.05038655 0.47437584 0.35717617]

Max: 0.9603621654026713
Min: 0.008373966382303366

Array normalizado: [0.85419012 1.         0.40891279 0.55364838 0.94342132 0.
 0.39843428 0.04413141 0.48950383 0.36639341]


## Exercicio 10

Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.


In [11]:
array = np.eye(6, 6, order='C')

for linha in range(0, 6):
    for coluna in range(0, 6):
        if linha == coluna:
            array[linha, coluna] = linha + 1

print(array)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


## Exercicio 11

Gere um array de 100 numeros inteiros e encontre o valor que mais se repete no array.


In [12]:
array = np.array(np.random.randint(1, 10, size=(100)))

repeticao = np.bincount(array).argmax()

print(array)
print(repeticao)

[6 2 6 1 1 6 7 2 6 6 7 9 3 7 3 1 5 9 5 9 7 8 4 3 8 6 3 7 7 2 6 5 2 9 5 5 2
 6 7 1 4 2 4 2 4 1 4 2 3 4 8 8 5 1 2 6 7 6 4 6 8 9 3 2 2 9 3 9 9 2 9 2 5 1
 4 4 9 2 6 3 6 3 9 4 3 3 9 9 3 6 7 8 2 3 3 1 4 3 6 1]
2


## Exercicio 12

Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.


In [13]:
array = np.eye(4, 4)

for linha in range(0, 4):
    for coluna in range(0, 4):
        if linha == coluna:
            array[linha, coluna] = 7

print(array)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


## Exercicio 13

Crie um array contendo os 10 primeiros numeros pares e calcule sua soma cumulativa.


In [14]:
array = np.arange(2, 21, 2)

print(array)

soma = np.cumsum(array)

print(soma)

[ 2  4  6  8 10 12 14 16 18 20]
[  2   6  12  20  30  42  56  72  90 110]


## Exercicio 14

Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo comprimento e encontre a media das diferencas.


In [15]:
array1 = np.array(np.random.randint(1, 11, size=10))
array2 = np.array(np.random.randint(1, 11, size=10))
print(array1, array2)

diferenca = array1 - array2
print(diferenca)

media = sum(diferenca)/10
print(media)

[ 8  3  2  4  2  6  8 10 10  7] [ 7 10  7  9  2  5  4  7  3  3]
[ 1 -7 -5 -5  0  1  4  3  7  4]
0.3


## Exercicio 15

Gere um array contendo 20 numeros e substitua todos os valores maiores que 50 por 50.


In [16]:
array = np.array(np.random.randint(1, 101, size=20))
print(array)
for n in array:
    if n > 50:
        array[array == n] = 50 
print(array)

[ 9 35 16 95  1 22 87 58 11 49 30 40 43 25 23 26 66 53 17 67]
[ 9 35 16 50  1 22 50 50 11 49 30 40 43 25 23 26 50 50 17 50]


## Exercicio 16

Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.


In [17]:
array = np.array(np.random.randint(1, 11, size=(12)))
print(array)

organiza = np.reshape(array, (3, 4))
print(organiza)

[ 2  1  9 10  6  1  2  5  8 10  7  5]
[[ 2  1  9 10]
 [ 6  1  2  5]
 [ 8 10  7  5]]


## Exercicio 17

Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada valor por sua posicao na matriz.


In [18]:
array = np.array(np.random.randint(1, 11, size=(4, 4)))
print(array)
for linha in range(0, 4):
    for coluna in range(0, 4):
        array[linha][coluna]

[[ 9 10  6  9]
 [10  6 10  7]
 [ 7  4  5  3]
 [ 9  2  8  9]]


## Exercicio 18

Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 5 por 0.


In [19]:
array = np.array(np.random.randint(1, 101, size=10))
print(array)
for n in array:
    if n % 5 == 0:
        array[array == n] = 0
print(array)

[49 47 56 21  4 73 65 99 38 48]
[49 47 56 21  4 73  0 99 38 48]


## Exercicio 19

Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o angulo entre eles (produto escalar normalizado).


In [48]:
array1 = np.array(np.random.randint(1, 21, size=20))
array2 = np.array(np.random.randint(1, 21, size=20))

produto_escalar = 0
print(f'{array1}\n{array2}\n')

for n, j in zip(array1, array2):
    conta = n * j
    produto_escalar += conta

print(f'Produto escalar: {produto_escalar}')

somaArray1 = 0
somaArray2 = 0
for n in array1:
    somaArray1 += n ** 2

for n in array2:
    somaArray2 += n ** 2

normaArray1 = somaArray1 ** 0.5
normaArray2 = somaArray2 ** 0.5

print(f'Normaa do array 1: {normaArray1}\nNorma do array 2: {normaArray2}')

produto_escalar_normalizado = produto_escalar / (normaArray1 * normaArray2)

print(f'Produto escalar normalizado: {produto_escalar_normalizado}')

def fatorial(i):
    conta = 1
    for n in range(i, 0, -1):
        conta = conta * n 
    return conta

def coseno_serie_taylor(x):
    resultado = 0
    for n in range(0, 100, 2):
        termo = (x ** n) / fatorial(n)
        if (n // 2) % 2 == 0:
            resultado = resultado + termo
        else:
            resultado = resultado - termo

    return resultado

menor_valor = float("inf")
melhor_angulo = 0
for angulo in range(181):

    radianos = angulo * (3.14/180)

    cos = coseno_serie_taylor(radianos)

    diferenca = cos - produto_escalar_normalizado


    if diferenca < 0:
        diferenca = diferenca * -1

    if diferenca < menor_valor:
        menor_valor = diferenca
        melhor_angulo = angulo
            
print(f'Melhor angulo !!!!!!! HAHAAHAHAHAHA: {melhor_angulo}')
print(f'Menor diferenca: {menor_valor}')

[ 5 13  3  9  9 17  8  6  3  6 17  9  2 18 18 18 15 19 16 11]
[17 16  1  8  5  5  5 15  2 12  5 18  6  8 10  5  9  7  5 14]

Produto escalar: 1881
Normaa do array 1: 55.749439459065414
Norma do array 2: 44.53088815642464
Produto escalar normalizado: 0.7576819361488921
Melhor angulo !!!!!!! HAHAAHAHAHAHA: 41
Menor diferenca: 0.0027344063396836926


## Exercicio 20

Crie uma matriz de numeros inteiros e encontre o valor minimo de cada linha.


In [58]:
array = np.array(np.random.randint(1, 11, size=(5,5)))
print(array)
for linha in array:
    menor = linha[0]

    for n in linha:
        if n < menor:
            menor = n

    print(menor)

[[ 2  1  8 10  1]
 [ 2  4  7  3 10]
 [ 9  5  7 10  4]
 [ 4  7  5  9  4]
 [ 1  3  8  5  4]]
1
2
4
4
1


# SciPy

## Exercicio 1

Calcule a integral da funcao f(x) = x^2 sin(x) no intervalo de 0 a pi.


## Exercicio 2

Resolva a equacao diferencial dy/dx = x - y, com y(0) = 1, no intervalo de 0 a 10.


## Exercicio 3

Encontre as raizes da funcao f(x) = x^4 - 3x^3 + 2 utilizando SciPy.


## Exercicio 4

Use a funcao de otimizacao de SciPy para maximizar f(x) = -x^2 + 4x + 1.


## Exercicio 5

Calcule a transformada de Fourier de um sinal composto de sin(2 pi t) e cos(4 pi t).


## Exercicio 6

Encontre a matriz inversa de uma matriz 5x5 de numeros aleatorios.


## Exercicio 7

Use a funcao de interpolacao cubica de SciPy para interpolar os dados (0, 0), (1, 2), (2, 3), (3, 5), (4, 4).


## Exercicio 8

Resolva o sistema de equacoes 3x + 2y = 5 e x + 4y = 6.


## Exercicio 9

Ajuste uma curva quadratica aos pontos (1, 2), (2, 4), (3, 5), (4, 7), (5, 8).


## Exercicio 10

Calcule a integral dupla da funcao f(x, y) = xy + x^2 no intervalo [0, 2] para x e [0, 1] para y.


## Exercicio 11

Encontre os autovalores e autovetores de uma matriz 4x4 de numeros inteiros aleatorios.


## Exercicio 12

Resolva a equacao e^x - x^2 = 0 para encontrar a raiz mais proxima de x = 1.


## Exercicio 13

Calcule o determinante de uma matriz 6x6 de numeros aleatorios entre -10 e 10.


## Exercicio 14

Utilize a funcao de otimizacao multivariada para minimizar f(x, y) = (x - 2)^2 + (y - 3)^2.


## Exercicio 15

Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.


In [ ]:
#fft

## Exercicio 16

Resolva a equacao diferencial de segunda ordem d^2y/dx^2 + y = 0, com condicoes iniciais y(0) = 1 e y'(0) = 0.


## Exercicio 17

Encontre a raiz cubica de 27 utilizando SciPy.


## Exercicio 18

Interpole os valores de uma funcao f(x) = x^2 nos pontos [1, 2, 3, 4, 5] utilizando spline cubica.


## Exercicio 19

Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.


## Exercicio 20

Resolva um sistema de equacoes lineares com tres variaveis utilizando SciPy.


# Pandas

In [59]:
import pandas as pd

## Exercicio 1

Crie um DataFrame contendo as colunas Produto, Preco e Quantidade com 5 produtos.


## Exercicio 2

Leia um arquivo Excel chamado vendas.xlsx e exiba as 10 primeiras linhas.


## Exercicio 3

Filtre um DataFrame para exibir apenas os valores onde a coluna Preco e maior que 100.


## Exercicio 4

Adicione uma coluna chamada Desconto ao DataFrame com 10% de desconto para todos os produtos.


## Exercicio 5

Remova as linhas do DataFrame que contenham valores nulos.


## Exercicio 6

Ordene o DataFrame pela coluna Produto em ordem alfabetica.


## Exercicio 7

Crie uma nova coluna chamada Total que seja o produto entre as colunas Preco e Quantidade.


## Exercicio 8

Agrupe o DataFrame pela coluna Categoria e calcule o total de produtos por categoria.


## Exercicio 9

Exporte o DataFrame resultante para um arquivo CSV chamado resultados.csv.


## Exercicio 10

Leia um arquivo CSV, renomeie as colunas e exiba as 5 ultimas linhas do DataFrame.


## Exercicio 11

Preencha os valores nulos de uma coluna numerica com a mediana dessa coluna.


## Exercicio 12

Verifique quais colunas de um DataFrame contem valores duplicados.


## Exercicio 13

Crie uma tabela dinamica a partir do DataFrame, calculando a soma de Quantidade por Categoria.


## Exercicio 14

Mescle dois DataFrames baseados em uma coluna comum chamada ID utilizando um join.


## Exercicio 15

Crie um DataFrame com dados faltantes e use a interpolacao linear para preenche-los.


## Exercicio 16

Crie um grafico de barras a partir de um DataFrame usando a biblioteca Pandas.


## Exercicio 17

Adicione uma coluna ao DataFrame que calcule o imposto (5%) sobre o valor da coluna Total.


## Exercicio 18

Exiba apenas as linhas de um DataFrame onde o nome do produto comeca com a letra B.


## Exercicio 19

Crie um DataFrame a partir de um dicionario de listas e calcule a media de cada coluna numerica.


## Exercicio 20

Agrupe os dados por uma coluna categorica e calcule a mediana de uma coluna numerica.


# Matplotlib

## Exercicio 1

Crie um grafico de linha para a funcao y = x^3 no intervalo de x = -10 ate x = 10.


## Exercicio 2

Plote um grafico de dispersao para 100 pontos aleatorios com uma paleta de cores baseada nos valores de y.


## Exercicio 3

Gere um histograma para 500 numeros inteiros gerados aleatoriamente entre 0 e 100.


## Exercicio 4

Crie um grafico de barras para 5 categorias com valores diferentes, colorindo cada barra de uma cor diferente.


## Exercicio 5

Faca um grafico de pizza para representar as porcentagens de quatro setores de mercado com rotulos personalizados.


## Exercicio 6

Plote dois graficos de linha em subplots diferentes: y1 = e^x e y2 = log(x).


## Exercicio 7

Crie um grafico de dispersao com tamanho dos pontos variando de acordo com os valores de y.


## Exercicio 8

Plote um grafico de linha com intervalos de confianca (sombramento) para a funcao y = sin(x).


## Exercicio 9

Adicione titulo, rotulos e uma grade personalizada a um grafico de linha.


## Exercicio 10

Plote tres graficos de linha em um unico grafico, cada um com uma cor e estilo de linha diferentes.


## Exercicio 11

Crie um grafico de barras empilhadas para tres categorias com tres grupos de valores.


## Exercicio 12

Plote um grafico de linha com uma funcao quadratica e ajuste os limites do eixo para focar nos valores x = -5 a x = 5.


## Exercicio 13

Gere um grafico de dispersao 3D para 100 pontos aleatorios utilizando Matplotlib.


## Exercicio 14

Crie um grafico de barras horizontal para 4 categorias com valores gerados aleatoriamente.


## Exercicio 15

Plote a funcao y = 1/x com x variando de 1 a 100.


## Exercicio 16

Crie um grafico de linha com titulos para cada eixo e adicione um rotulo de texto no ponto x = 5.


## Exercicio 17

Plote um grafico de linha e salve-o como um arquivo PDF.


## Exercicio 18

Crie um grafico de barras com valores positivos e negativos e use diferentes cores para cada tipo de valor.


## Exercicio 19

Plote um grafico de linha com duas series e adicione uma legenda para diferencia-las.


## Exercicio 20

Adicione uma grade com espacamento personalizado a um grafico de linha para y = x^2.
